name: Run Commitlint on PR

on:
  push:
    branches:
      - "*"
    branches-ignore:
      - "main"
jobs:
  run-commitlint-on-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.1
      - name: install commitlint
        run: npm install -g @commitlint/config-conventional
      - name: configure commitlint rule
        run: >
          echo "{ extends: ['@commitlint/config-conventional'] }" > .commitlintrc
      - name: Validate all commits from PR
        run: echo ${{ github.event.head_commit.message }} | npx commitlint
